#!/bin/bash

# MySQL credentials
MYSQL_USER="root"
MYSQL_PASSWORD="root"
DATABASE_NAME="TPCH"

# MySQL Docker container name
DOCKER_CONTAINER_NAME="mysql-server"

# Directory containing .tbl files
TPCH_DIR="/etc/tpch" # Put mounted container directory here where TPC-H dataset is located

# Enable local_infile
echo "Enabling local_infile"
docker exec -i $DOCKER_CONTAINER_NAME mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SET GLOBAL local_infile = 1;"

# Create the TPCH database with utf8mb4 character set
echo "Creating database $DATABASE_NAME"
docker exec -i $DOCKER_CONTAINER_NAME mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE $DATABASE_NAME character set utf8mb4;"

# SQL statements to create TPC-H tables
create_statements=(
"CREATE TABLE NATION (N_NATIONKEY INTEGER primary key, N_NAME CHAR(25) NOT NULL, N_REGIONKEY INTEGER NOT NULL, N_COMMENT VARCHAR(152));"
"CREATE TABLE REGION (R_REGIONKEY INTEGER primary key, R_NAME CHAR(25) NOT NULL, R_COMMENT VARCHAR(152));"
"CREATE TABLE PART (P_PARTKEY INTEGER primary key, P_NAME VARCHAR(55) NOT NULL, P_MFGR CHAR(25) NOT NULL, P_BRAND CHAR(10) NOT NULL, P_TYPE VARCHAR(25) NOT NULL, P_SIZE INTEGER NOT NULL, P_CONTAINER CHAR(10) NOT NULL, P_RETAILPRICE DECIMAL(15,2) NOT NULL, P_COMMENT VARCHAR(23) NOT NULL);"
"CREATE TABLE SUPPLIER (S_SUPPKEY INTEGER primary key, S_NAME CHAR(25) NOT NULL, S_ADDRESS VARCHAR(40) NOT NULL, S_NATIONKEY INTEGER NOT NULL, S_PHONE CHAR(15) NOT NULL, S_ACCTBAL DECIMAL(15,2) NOT NULL, S_COMMENT VARCHAR(101) NOT NULL);"
"CREATE TABLE PARTSUPP (PS_PARTKEY INTEGER NOT NULL, PS_SUPPKEY INTEGER NOT NULL, PS_AVAILQTY INTEGER NOT NULL, PS_SUPPLYCOST DECIMAL(15,2) NOT NULL, PS_COMMENT VARCHAR(199) NOT NULL, primary key (ps_partkey, ps_suppkey));"
"CREATE TABLE CUSTOMER (C_CUSTKEY INTEGER primary key, C_NAME VARCHAR(25) NOT NULL, C_ADDRESS VARCHAR(40) NOT NULL, C_NATIONKEY INTEGER NOT NULL, C_PHONE CHAR(15) NOT NULL, C_ACCTBAL DECIMAL(15,2) NOT NULL, C_MKTSEGMENT CHAR(10) NOT NULL, C_COMMENT VARCHAR(117) NOT NULL);"
"CREATE TABLE ORDERS (O_ORDERKEY INTEGER primary key, O_CUSTKEY INTEGER NOT NULL, O_ORDERSTATUS CHAR(1) NOT NULL, O_TOTALPRICE DECIMAL(15,2) NOT NULL, O_ORDERDATE DATE NOT NULL, O_ORDERPRIORITY CHAR(15) NOT NULL, O_CLERK CHAR(15) NOT NULL, O_SHIPPRIORITY INTEGER NOT NULL, O_COMMENT VARCHAR(79) NOT NULL);"
"CREATE TABLE LINEITEM (L_ORDERKEY INTEGER NOT NULL, L_PARTKEY INTEGER NOT NULL, L_SUPPKEY INTEGER NOT NULL, L_LINENUMBER INTEGER NOT NULL, L_QUANTITY DECIMAL(15,2) NOT NULL, L_EXTENDEDPRICE DECIMAL(15,2) NOT NULL, L_DISCOUNT DECIMAL(15,2) NOT NULL, L_TAX DECIMAL(15,2) NOT NULL, L_RETURNFLAG CHAR(1) NOT NULL, L_LINESTATUS CHAR(1) NOT NULL, L_SHIPDATE DATE NOT NULL, L_COMMITDATE DATE NOT NULL, L_RECEIPTDATE DATE NOT NULL, L_SHIPINSTRUCT CHAR(25) NOT NULL, L_SHIPMODE CHAR(10) NOT NULL, L_COMMENT VARCHAR(44) NOT NULL, primary key(L_ORDERKEY,L_LINENUMBER));"
)

# List of TPC-H tables
table_files=("nation" "region" "part" "supplier" "partsupp" "customer" "orders" "lineitem")
tables=("NATION" "REGION" "PART" "SUPPLIER" "PARTSUPP" "CUSTOMER" "ORDERS" "LINEITEM")

# Create each table
for i in "${!tables[@]}"
do
    file_loc=${table_files[$i]}
    table=${tables[$i]}
    create_statement=${create_statements[$i]}

    echo "Creating table $table"
    docker exec -i $DOCKER_CONTAINER_NAME mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $DATABASE_NAME -e "$create_statement"

    echo "Loading data into $table from ${table}.tbl"
    docker exec -i $DOCKER_CONTAINER_NAME mysql -u$MYSQL_USER -p$MYSQL_PASSWORD $DATABASE_NAME -e \
    "LOAD DATA INFILE '$TPCH_DIR/${file_loc}.tbl' INTO TABLE $table FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';"
done

echo "Database setup and data loading complete."
